import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('purpose', models.TextField()),
                ('schedule', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingOutBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('normalized_description', models.CharField(db_index=True, max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'lines of business',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostalCodeCentroid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postal_code', models.CharField(max_length=5, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('no_change', 'No change')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tracker.automationrule')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('normalized_city', models.CharField(blank=True, max_length=120)),
                ('display_key', models.CharField(max_length=400, unique=True)),
                ('facility_type', models.CharField(db_index=True, default='Hospital', max_length=100)),
                ('phone_display', models.CharField(blank=True, max_length=80)),
                ('phone_normalized', models.CharField(blank=True, max_length=32)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordinate_provenance', models.CharField(blank=True, max_length=80)),
                ('data_quality_status', models.CharField(choices=[('verified', 'Verified'), ('review', 'Needs review'), ('missing_coordinates', 'Missing coordinates'), ('conflict', 'Conflicting source records')], db_index=True, default='verified', max_length=32)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
                ('importer_version', models.CharField(blank=True, max_length=40)),
                ('import_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provenance', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name', 'city'],
                'indexes': [models.Index(fields=['active', 'facility_type'], name='tracker_fac_active_398436_idx'), models.Index(fields=['postal_code', 'active'], name='tracker_fac_postal__dd782d_idx'), models.Index(fields=['data_quality_status', 'name'], name='tracker_fac_data_qu_96304a_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'normalized_city'), name='unique_facility_identity')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCallGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_key', models.CharField(max_length=64, unique=True)),
                ('week_start', models.DateField(db_index=True)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution', models.TextField(blank=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_groups', to='tracker.diagnosis')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_groups', to='tracker.facility')),
            ],
            options={
                'ordering': ['-week_start', 'facility__name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_kind', models.CharField(max_length=16)),
                ('source_hash', models.CharField(max_length=64)),
                ('importer_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='previewed', max_length=16)),
                ('summary', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_row', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('issue_codes', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tracker.importbatch')),
            ],
            options={
                'ordering': ['source_sheet', 'source_row'],
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization_number', models.CharField(max_length=64, unique=True)),
                ('member_postal_code', models.CharField(max_length=5)),
                ('referral_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_authorizations', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='tracker.diagnosis')),
                ('line_of_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='tracker.lineofbusiness')),
                ('referral_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='tracker.referralreason')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='tracker.specialty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_at', models.DateTimeField(db_index=True)),
                ('phone_snapshot', models.CharField(blank=True, max_length=80)),
                ('did_not_leave_vm', models.BooleanField(default=False)),
                ('accepting_new_patients', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown'), ('not_applicable', 'N/A'), ('unable_to_tell_without_triage', 'Unable to tell without triage')], default='unknown', max_length=40)),
                ('can_treat_diagnosis', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown'), ('not_applicable', 'N/A'), ('unable_to_tell_without_triage', 'Unable to tell without triage')], default='unknown', max_length=40)),
                ('can_schedule_within_four_weeks', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown'), ('not_applicable', 'N/A'), ('unable_to_tell_without_triage', 'Unable to tell without triage'), ('urgent_referral_required', 'Urgent referral required')], default='unknown', max_length=40)),
                ('booking_out_notes', models.CharField(blank=True, max_length=160)),
                ('urgent_referral_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('referral_type', models.CharField(blank=True, max_length=120)),
                ('out_of_network_reason', models.TextField(blank=True)),
                ('specialty_confirmed', models.BooleanField(default=False)),
                ('use_in_fdm', models.BooleanField(default=False)),
                ('repeat_call_reason', models.TextField(blank=True)),
                ('result_code', models.CharField(db_index=True, editable=False, max_length=64)),
                ('result_phrase', models.CharField(editable=False, max_length=255)),
                ('recommendation', models.CharField(editable=False, max_length=255)),
                ('rule_version', models.CharField(default='2026.1', editable=False, max_length=24)),
                ('next_review_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
                ('importer_version', models.CharField(blank=True, max_length=40)),
                ('import_fingerprint', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('original_cached_result_phrase', models.CharField(blank=True, max_length=255)),
                ('normalization_issues', models.JSONField(blank=True, default=list)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='tracker.authorization')),
                ('booking_out_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='tracker.bookingoutbucket')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_calls', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='tracker.diagnosis')),
                ('duplicate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='tracker.duplicatecallgroup')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='tracker.facility')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='tracker.specialty')),
            ],
            options={
                'ordering': ['-call_at', 'facility__name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(db_index=True, max_length=60)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source_fingerprint', models.CharField(max_length=64, unique=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(db_index=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('automation_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='tracker.facility')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='tracker.importrowresult')),
                ('provider_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='tracker.providercall')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown'), ('not_applicable', 'N/A'), ('unable_to_tell_without_triage', 'Unable to tell without triage')], default='unknown', max_length=40)),
                ('confirmed', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
                ('import_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_links', to='tracker.facility')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_links', to='tracker.specialty')),
            ],
            options={
                'ordering': ['facility__name', 'specialty__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('source_hash', 'importer_version'), name='unique_import_batch'),
        ),
        migrations.AddConstraint(
            model_name='importrowresult',
            constraint=models.UniqueConstraint(fields=('batch', 'source_sheet', 'source_row'), name='unique_import_source_row'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['status', 'due_date', 'priority'], name='tracker_rev_status_47fd1a_idx'),
        ),
        migrations.AddIndex(
            model_name='providercall',
            index=models.Index(fields=['facility', 'diagnosis', 'call_at'], name='tracker_pro_facilit_2823a6_idx'),
        ),
        migrations.AddIndex(
            model_name='providercall',
            index=models.Index(fields=['authorization', 'result_code'], name='tracker_pro_authori_8d2173_idx'),
        ),
        migrations.AddIndex(
            model_name='providercall',
            index=models.Index(fields=['caller', 'call_at'], name='tracker_pro_caller__92f743_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilityspecialty',
            constraint=models.UniqueConstraint(fields=('facility', 'specialty'), name='unique_facility_specialty'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['status', 'created_at'], name='tracker_aut_status_f1d40f_idx'),
        ),
    ]
